[package]
name = "whistle_parser"
version = "0.1.1"
authors = ["the Whistle authors"]
edition = "2021"

[dependencies]
whistle_common = { path = "../common/" }
whistle_ast = { path = "../ast/" }
whistle_lexer = { path = "../lexer/" }
whistle_preprocessor = { path = "../preprocessor/" }
